defaults:
  - _self_
  - model: raev2_codec_tdown
  - dataset: doom

actions: ${dataset.actions}

wandb:
  entity: null
  project: mira-codec
  name: codec
  group: null
  mode: online  # "disabled" to turn off, "offline" to log locally only
  remove_old_runs: false

run:
  seed: 28
  steps: 250_001
  batch_size: 4
  checkpoint_every: "5%"
  checkpoint_keep_recent: 1
  checkpoint_keep_permanent_every: -1
  log_every: "1%"
  output_dir: "train_codec_logs"
  compile: true
  viz_every: 1000
  continue_from: null
  finetune_from: null
  latents_ema_decay: 0.99

dataloader:
  num_workers: 6
  shuffle_buffer_size: 100

validation:
  batch_size: null  # null to use the same batch size as training
  val_first: true
  val_n_samples: 1024
  val_every: "2%"

optim:
  optimizer:
    lr: 1e-4
    betas: [0.9, 0.95]
    weight_decay: 0.1
  scheduler:
    warmup_steps: 1000
    constant_steps: 0
    decay_steps: 249_000  # 0 to disable cosine decay; otherwise ~run.steps - warmup_steps
    min_lr: 1e-6
  model_ema_decay: 0.9999  # 0.0 to disable
